name: HealthConnect – CSV to JSON Converter

on:
  workflow_dispatch:
  push:
    paths:
      - 'modules/health_insight_hub/sample_input/*.csv'

jobs:
  convert-csv:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: \U0001F4E5 Checkout repository
        uses: actions/checkout@v3

      - name: \U0001F40D Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: \U0001F4E6 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: \U0001F504 Convert CSVs to JSON
        run: |
          for csv in modules/health_insight_hub/sample_input/*.csv; do
            date_key=$(basename "$csv" .csv | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
            output_path="data/health/$date_key.json"
            echo "Processing $csv → $output_path"
            python -c "
from modules.health_insight_hub.data_parser import parse_csv_to_json;
parse_csv_to_json('$csv', '$output_path')"
          done

      - name: \U0001F4E4 Commit JSON logs to repo
        run: |
          git config user.name "FlexiusBot"
          git config user.email "flexius@users.noreply.github.com"
          git add data/health/*.json
          timestamp=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          git commit -m "\U0001F4BE Auto-parsed health CSVs to JSON – $timestamp" || echo "No changes to commit"
          git push origin main
