name: Export OpenAPI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: |
          pip install fastapi uvicorn pydantic
          python scripts/export_openapi.py > openapi.json
      - uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi.json
