name: HealthConnect – Weekly Report Export

on:
  schedule:
    - cron: '0 3 * * 1'    # Every Monday at 11:00 AM PHT
  workflow_dispatch:

jobs:
  generate-weekly-pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: \U0001F4E5 Checkout repository
        uses: actions/checkout@v3

      - name: \U0001F40D Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: \U0001F4E6 Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib reportlab

      - name: \U0001F5A8 Run PDF Export Script
        run: |
          mkdir -p reports/health/
          python -c "
from modules.health_insight_hub.pdf_exporter import export_weekly_pdf;
export_weekly_pdf('data/health', 'reports/health/weekly_$(date +%Y-%m-%d).pdf')"

      - name: \U0001F4E4 Commit PDF to repository
        run: |
          git config user.name "FlexiusBot"
          git config user.email "flexius@users.noreply.github.com"
          git add reports/health/*.pdf
          timestamp=$(date -u +'"%Y-%m-%d %H:%M:%S UTC"')
          git commit -m "\U0001F4CA Weekly Health Report Exported – $timestamp" || echo "No changes to commit"
          git push origin main
