name: Publish Plugin
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: |
          pip install fastapi pydantic
          export PYTHONPATH=$PWD
          python scripts/export_openapi.py > api/.well-known/openapi.json
          python scripts/update_plugin_manifest.py
      - name: Commit updated plugin
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if git diff --quiet; then echo "No changes"; else git add api/.well-known/ai-plugin.json api/.well-known/openapi.json; git commit -m "chore: update plugin"; git push; fi
        env:
          CONNECTOR_PUBLIC_URL: ${{ secrets.CONNECTOR_PUBLIC_URL }}
